((and (role in {visitor}) (time in [8, 16])), (EF (room_id in {mr})))
((role in {visitor}), (not (EU (not (room_id in {lob})) (room_id in {mr}))))
((and (role in {employee}) (time in [8, 16])), (EF (room_id in {bur})))
((and (role in {employee}) validPin), (EF (room_id in {bur})))
((not (role in {employee})), (not (EF (room_id in {bur}))))
((and (and (not validPin) (time in [0, 7])) (role in {employee})), (not (EF (room_id in {bur}))))
((and (and (not validPin) (time in [17, 24])) (role in {employee})), (not (EF (room_id in {bur}))))
