((and (role in {visitor}) (time in [8, 20])), (EF (room_id in {mr})))
((role in {visitor}), (not (EU (not (room_id in {lob})) (room_id in {mr}))))
((and (role in {employee}) (time in [8, 20])), (EF (room_id in {bur})))
((and (role in {employee}) validPin), (EF (room_id in {bur})))
((not (role in {employee})), (not (EF (zone in {secured}))))
