SECTION_SYNTHESIS = 'SYNTHESIS'
OPTION_STRUCTURE='STRUCTURE'
OPTION_SUBJECT_ATTRIBUTES='SUBJECT_ATTRIBUTES'
OPTION_RESOURCE_ATTRIBUTES='RESOURCE_ATTRIBUTES'
OPTION_REQUIREMENTS='REQUIREMENTS'
OPTION_FIXED_GRAMMAR='FIXED_GRAMMAR'
OPTION_OUTPUT='OUTPUT'

SECTION_GRAMMAR = 'GRAMMAR'
OPTION_NUMBER_OF_ENUMERATED_ATTRIBUTES='NUMBER_OF_ENUMERATED'
OPTION_NUMBER_OF_NUMERIC_ATTRIBUTES='NUMBER_OF_NUMERIC'
OPTION_NUMBER_OF_DISJUNCTIONS='NUMBER_OF_DISJUNCTIONS'

OUTPUT='synth.out'